# ComfyUI Docker Compose File v1.0.1 created by John Aldred
# modified by ma-he-sh

services:
  proxy:
    image: nginx:alpine
    container_name: comfyui_proxy
    ports:
      - "8188:80"  # You still access it via port 8188
    volumes:
      - ./secure/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secure/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - comfyk
    networks:
      - comfy_net

  comfyk:
    build:
      dockerfile: Dockerfile
    image: comfyui:latest
    container_name: comfyui
    volumes:
      # persist your models, output, and settings:
      - ./models:/app/ComfyUI/models

      # persist your output images:
      - ./output:/app/ComfyUI/output
      
      # persist all your settings & extra nodes:
      - ./settings:/app/ComfyUI/user/default:rw

      # persist just your saved flows (overrides the workflows/ in default):
      - ./flows:/app/ComfyUI/user/default/workflows:rw
    
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]

    networks:
      - comfy_net

networks:
  comfy_net:
    driver: bridge
